# test_data_spending.py

test_examples = [
    # === Еда (12) ===
    {"input": "Купил кофе за 200 ₽", "main_category": "Еда", "psych_category": "Радость"},
    {"input": "Заказал пиццу на ужин — 850 ₽", "main_category": "Еда", "psych_category": "Комфорт"},
    {"input": "Продукты на неделю: 5200 ₽", "main_category": "Еда", "psych_category": "Необходимость"},
    {"input": "Съел бургер после работы", "main_category": "Еда", "psych_category": "Комфорт"},
    {"input": "Купил детям сладости в магазине", "main_category": "Еда", "psych_category": "Необходиость"},
    {"input": "Обед в офисе — 350 ₽", "main_category": "Еда", "psych_category": "Необходимость"},
    {"input": "Пирожное на десерт — 200 ₽", "main_category": "Еда", "psych_category": "Радость"},
    {"input": "Купил фрукты и овощи", "main_category": "Еда", "psych_category": "Забота"},
    {"input": "Потратил на ужин с друзьями", "main_category": "Еда", "psych_category": "Радость"},
    {"input": "Завтрак в кафе — 400 ₽", "main_category": "Еда", "psych_category": "Комфорт"},
    {"input": "Купил молоко и хлеб", "main_category": "Еда", "psych_category": "Необходимость"},
    {"input": "Сок на прогулке — 150 ₽", "main_category": "Еда", "psych_category": "Радость"},

    # === Транспорт (10) ===
    {"input": "Заправил машину на 3500 ₽", "main_category": "Транспорт", "psych_category": "Необходимость"},
    {"input": "Такси до дома после встречи — 400 ₽", "main_category": "Транспорт", "psych_category": "Комфорт"},
    {"input": "Купил проездной на месяц", "main_category": "Транспорт", "psych_category": "Необходимость"},
    {"input": "Потратил на каршеринг в отпуске", "main_category": "Транспорт", "psych_category": "Радость"},
    {"input": "Билет на электричку — 250 ₽", "main_category": "Транспорт", "psych_category": "Необходимость"},
    {"input": "Оплатил парковку у ТЦ", "main_category": "Транспорт", "psych_category": "Комфорт"},
    {"input": "Купил билет на поезд", "main_category": "Транспорт", "psych_category": "Необходимость"},
    {"input": "Такси до аэропорта — 1200 ₽", "main_category": "Транспорт", "psych_category": "Комфорт"},
    {"input": "Метро до центра — 60 ₽", "main_category": "Транспорт", "psych_category": "Необходимость"},
    {"input": "Аренда велосипеда — 300 ₽", "main_category": "Транспорт", "psych_category": "Радость"},

    # === Здоровье (10) ===
    {"input": "Оплатил абонемент в зал — 3000 ₽", "main_category": "Здоровье", "psych_category": "Необходимость"},
    {"input": "Купил витамины в аптеке", "main_category": "Здоровье", "psych_category": "Забота"},
    {"input": "Посетил стоматолога — 7000 ₽", "main_category": "Здоровье", "psych_category": "Необходимость"},
    {"input": "Массаж после тяжелой недели", "main_category": "Здоровье", "psych_category": "Комфорт"},
    {"input": "Лекарства от простуды — 600 ₽", "main_category": "Здоровье", "psych_category": "Необходимость"},
    {"input": "Анализы в лаборатории", "main_category": "Здоровье", "psych_category": "Необходимость"},
    {"input": "Купил бандаж для спины", "main_category": "Здоровье", "psych_category": "Забота"},
    {"input": "Сеанс у психолога", "main_category": "Здоровье", "psych_category": "Комфорт"},
    {"input": "Тест на витамины — 1500 ₽", "main_category": "Здоровье", "psych_category": "Забота"},
    {"input": "Купил термометр", "main_category": "Здоровье", "psych_category": "Необходимость"},

    # === Одежда (8) ===
    {"input": "Купил новую куртку за 7500", "main_category": "Одежда", "psych_category": "Комфорт"},
    {"input": "Носки и нижнее бельё — 1200 ₽", "main_category": "Одежда", "psych_category": "Необходимость"},
    {"input": "Кроссовки для прогулок — 4000 ₽", "main_category": "Одежда", "psych_category": "Комфорт"},
    {"input": "Футболки на лето — 2000 ₽", "main_category": "Одежда", "psych_category": "Необходимость"},
    {"input": "Платье на праздник", "main_category": "Одежда", "psych_category": "Радость"},
    {"input": "Купил пижаму", "main_category": "Одежда", "psych_category": "Комфорт"},
    {"input": "Шапка и перчатки", "main_category": "Одежда", "psych_category": "Необходимость"},
    {"input": "Спортивный костюм", "main_category": "Одежда", "psych_category": "Забота"},

    # === Развлечения (10) ===
    {"input": "Билеты в кино на двоих — 1200 ₽", "main_category": "Развлечения", "psych_category": "Радость"},
    {"input": "Подписка на Netflix — 600 ₽", "main_category": "Развлечения", "psych_category": "Комфорт"},
    {"input": "Купил билет на концерт", "main_category": "Развлечения", "psych_category": "Радость"},
    {"input": "Посетил выставку", "main_category": "Развлечения", "psych_category": "Радость"},
    {"input": "Купил игры на телефон — 500 ₽", "main_category": "Развлечения", "psych_category": "Комфорт"},
    {"input": "Билет в театр", "main_category": "Развлечения", "psych_category": "Радость"},
    {"input": "Подписка на Spotify — 199 ₽", "main_category": "Развлечения", "psych_category": "Комфорт"},
    {"input": "Поход в боулинг", "main_category": "Развлечения", "psych_category": "Радость"},
    {"input": "Книга для души — 600 ₽", "main_category": "Развлечения", "psych_category": "Комфорт"},
    {"input": "Билет на фестиваль", "main_category": "Развлечения", "psych_category": "Радость"},

    # === Образование (10) ===
    {"input": "Оплатил курс по финансовой грамотности", "main_category": "Образование", "psych_category": "Забота"},
    {"input": "Купил учебники для университета", "main_category": "Образование", "psych_category": "Необходимость"},
    {"input": "Индивидуальные уроки английского — 2500 ₽", "main_category": "Образование", "psych_category": "Забота"},
    {"input": "Подписка на Coursera — 990 ₽", "main_category": "Образование", "psych_category": "Необходимость"},
    {"input": "Книга по программированию", "main_category": "Образование", "psych_category": "Забота"},
    {"input": "Вебинар по карьере", "main_category": "Образование", "psych_category": "Забота"},
    {"input": "Оплатил репетитора", "main_category": "Образование", "psych_category": "Забота"},
    {"input": "Канцелярия для учёбы", "main_category": "Образование", "psych_category": "Необходимость"},
    {"input": "Онлайн-курс по дизайну", "main_category": "Образование", "psych_category": "Забота"},
    {"input": "Словарь английского языка", "main_category": "Образование", "psych_category": "Необходимость"},

    # === Связь и ЖКХ (10) ===
    {"input": "Оплатил интернет за месяц", "main_category": "Связь", "psych_category": "Необходимость"},
    {"input": "Пополнил телефон на 500 ₽", "main_category": "Связь", "psych_category": "Необходимость"},
    {"input": "Заплатил за ЖКХ", "main_category": "ЖКХ", "psych_category": "Необходимость"},
    {"input": "Счет за электричество — 1200 ₽", "main_category": "ЖКХ", "psych_category": "Необходимость"},
    {"input": "Вода и газ за прошлый месяц", "main_category": "ЖКХ", "psych_category": "Необходимость"},
    {"input": "Облачное хранилище — 300 ₽", "main_category": "Связь", "psych_category": "Необходимость"},
    {"input": "Тариф на мобильную связь", "main_category": "Связь", "psych_category": "Необходимость"},
    {"input": "Ремонт счётчиков — 2000 ₽", "main_category": "ЖКХ", "psych_category": "Необходимость"},
    {"input": "Домофон и интернет", "main_category": "Связь", "psych_category": "Комфорт"},
    {"input": "Оплата за вывоз мусора", "main_category": "ЖКХ", "psych_category": "Необходимость"},

    # === Подарки, Дом, Финансы, Прочее (30) ===
    {"input": "Купил подарок другу", "main_category": "Подарки", "psych_category": "Забота"},
    {"input": "Цветы маме — 800 ₽", "main_category": "Подарки", "psych_category": "Забота"},
    {"input": "Подарок коллеге", "main_category": "Подарки", "psych_category": "Забота"},
    {"input": "Сувениры из отпуска", "main_category": "Подарки", "psych_category": "Радость"},
    {"input": "Купил лампочки", "main_category": "Дом/ремонт", "psych_category": "Необходимость"},
    {"input": "Новые шторы — 3500 ₽", "main_category": "Дом/ремонт", "psych_category": "Комфорт"},
    {"input": "Ремонт сантехники — 6000 ₽", "main_category": "Дом/ремонт", "psych_category": "Необходимость"},
    {"input": "Купил диван", "main_category": "Дом/ремонт", "psych_category": "Комфорт"},
    {"input": "Оплатил страховку", "main_category": "Финансы", "psych_category": "Необходимость"},
    {"input": "Комиссия за перевод", "main_category": "Финансы", "psych_category": "Необходимость"},
    {"input": "Подписка на трекер расходов", "main_category": "Финансы", "psych_category": "Забота"},
    {"input": "Снял деньги в банкомате", "main_category": "Прочее", "psych_category": "Необходимость"},
    {"input": "Пожертвовал на благотворительность", "main_category": "Прочее", "psych_category": "Забота"},
    {"input": "Купил лотерейный билет", "main_category": "Прочее", "psych_category": "Радость"},
    {"input": "Оплатил доставку еды", "main_category": "Еда", "psych_category": "Комфорт"},
    {"input": "Купил наушники", "main_category": "Электроника", "psych_category": "Комфорт"},
    {"input": "Потратил на музыку", "main_category": "Развлечения", "psych_category": "Комфорт"},
    {"input": "Оплатил мобильный банк", "main_category": "Финансы", "psych_category": "Необходимость"},
    {"input": "Купил книгу", "main_category": "Образование", "psych_category": "Забота"},
    {"input": "Консультация психолога", "main_category": "Здоровье", "psych_category": "Забота"},
    {"input": "Билет в музей", "main_category": "Развлечения", "psych_category": "Радость"},
    {"input": "Спортивное питание", "main_category": "Здоровье", "psych_category": "Забота"},
    {"input": "Доставка подарка", "main_category": "Подарки", "psych_category": "Забота"},
    {"input": "Еда в дороге", "main_category": "Еда", "psych_category": "Необходимость"},
    {"input": "Новый телефон — 60 000 ₽", "main_category": "Связь", "psych_category": "Комфорт"},
    {"input": "Заплатил за психолога онлайн — 2500 ₽", "main_category": "Здоровье", "psych_category": "Забота"},
    {"input": "Купил детские игрушки в магазине", "main_category": "Другое", "psych_category": "Забота"},
    {"input": "Случайно оформил подписку на стриминг — 499 ₽", "main_category": "Развлечения", "psych_category": "Импульс"},
    {"input": "Пожертвовал на помощь животным", "main_category": "Другое", "psych_category": "Забота"},
    {"input": "Купил билет на онлайн-марафон по осознанности", "main_category": "Образование", "psych_category": "Развитие"},
    {"input": "Заплатил за ремонт наушников", "main_category": "Связь", "psych_category": "Необходимость"},
    {"input": "Взял такси под дождём — 380 ₽", "main_category": "Транспорт", "psych_category": "Комфорт"},
    {"input": "Купил шоколадку на кассе — импульс", "main_category": "Еда", "psych_category": "Импульс"},
    {"input": "Оплатил членство в профсоюзе", "main_category": "Другое", "psych_category": "Необходимость"},
    {"input": "Заказал еду, потому что было лень готовить", "main_category": "Еда", "psych_category": "Комфорт"},
    {"input": "Купил новогоднюю ёлку", "main_category": "Жилье", "psych_category": "Радость"},
    {"input": "Потратил на онлайн-курс по финансовой грамотности", "main_category": "Образование", "psych_category": "Развитие"},
    {"input": "Купил аптечку в дорогу", "main_category": "Здоровье", "psych_category": "Забота"},
    {"input": "Оплатил доставку подарка бабушке", "main_category": "Другое", "psych_category": "Забота"},
    {"input": "Купил билет на каток с детьми", "main_category": "Развлечения", "psych_category": "Радость"},
    {"input": "Витамины для ребёнка", "main_category": "Здоровье", "psych_category": "Забота"}
    
]