test_examples = [
    {"input": "Купил кофе за 200 ₽", "intent": "spending"},
    {"input": "Заправил машину на 3500 ₽", "intent": "spending"},
    {"input": "Потратил 5000 на еду", "intent": "spending"},
    {"input": "Оплатил подписку на Spotify", "intent": "spending"},
    {"input": "Снял деньги в банкомате", "intent": "spending"},
    {"input": "Купил билет на концерт", "intent": "spending"},
    {"input": "Заплатил за ЖКХ", "intent": "spending"},
    {"input": "Потратил на такси 400 ₽", "intent": "spending"},
    {"input": "Оплатил интернет", "intent": "spending"},
    {"input": "Купил новый телефон", "intent": "spending"},
    {"input": "Сходил в кино и потратил 1200 ₽", "intent": "spending"},
    {"input": "Оплатил обучение", "intent": "spending"},
    {"input": "Купил продукты на неделю", "intent": "spending"},
    {"input": "Потратил на подарок 3000 ₽", "intent": "spending"},
    {"input": "Оплатил страховку", "intent": "spending"},
    {"input": "Снял наличные на мелкие расходы", "intent": "spending"},
    {"input": "Купил одежду", "intent": "spending"},
    {"input": "Заплатил за ремонт", "intent": "spending"},
    {"input": "Потратил на отпуск", "intent": "spending"},
    {"input": "Оплатил доставку еды", "intent": "spending"},
    {"input": "Купил книги", "intent": "spending"},
    {"input": "Потратил на лекарства", "intent": "spending"},
    {"input": "Заплатил за парковку", "intent": "spending"},
    {"input": "Оплатил комиссию банка", "intent": "spending"},
    {"input": "Сегодня потратил больше обычного", "intent": "spending"},

    # === goal (25 примеров) ===
    {"input": "Хочу накопить на машину", "intent": "goal"},
    {"input": "Планирую отпуск в Италии", "intent": "goal"},
    {"input": "Мечтаю о новом ноутбуке", "intent": "goal"},
    {"input": "Хочу собрать на первый взнос по ипотеке", "intent": "goal"},
    {"input": "Собираю деньги на свадьбу", "intent": "goal"},
    {"input": "Планирую накопить на обучение", "intent": "goal"},
    {"input": "Хочу купить квартиру", "intent": "goal"},
    {"input": "Мечтаю о новом iPhone", "intent": "goal"},
    {"input": "Собираю на отпуск", "intent": "goal"},
    {"input": "Хочу накопить на ремонт", "intent": "goal"},
    {"input": "Планирую бюджет на крупную покупку", "intent": "goal"},
    {"input": "Хочу создать финансовую подушку", "intent": "goal"},
    {"input": "Собираю на подарок родителям", "intent": "goal"},
    {"input": "Хочу открыть свой бизнес", "intent": "goal"},
    {"input": "Планирую накопить на машину за год", "intent": "goal"},
    {"input": "Хочу купить дачу", "intent": "goal"},
    {"input": "Собираю на новый телевизор", "intent": "goal"},
    {"input": "Мечтаю о путешествии мечты", "intent": "goal"},
    {"input": "Хочу накопить на детей", "intent": "goal"},
    {"input": "Планирую накопить 500 тысяч", "intent": "goal"},
    {"input": "Хочу купить электросамокат", "intent": "goal"},
    {"input": "Собираю на курсы английского", "intent": "goal"},
    {"input": "Хочу накопить на новый холодильник", "intent": "goal"},
    {"input": "Планирую сформировать резерв", "intent": "goal"},
    {"input": "Хочу накопить на Новый год", "intent": "goal"},

    # === goals (10 примеров) ===
    {"input": "Покажи мои цели", "intent": "goals"},
    {"input": "Где мои финансовые цели?", "intent": "goals"},
    {"input": "Выведи список целей", "intent": "goals"},
    {"input": "Какие у меня цели?", "intent": "goals"},
    {"input": "Посмотреть цели", "intent": "goals"},
    {"input": "Где я там накапливаю?", "intent": "goals"},
    {"input": "Что у меня в планах по накоплениям?", "intent": "goals"},
    {"input": "Покажи, сколько я уже накопил", "intent": "goals"},
    {"input": "Мои цели по расходам", "intent": "goals"},
    {"input": "Напомни мои цели", "intent": "goals"},

    # === visualization (10 примеров) ===
    {"input": "Покажи график моих трат", "intent": "visualization"},
    {"input": "Хочу увидеть статистику расходов", "intent": "visualization"},
    {"input": "Построй диаграмму по категориям", "intent": "visualization"},
    {"input": "Где моя статистика?", "intent": "visualization"},
    {"input": "Покажи, сколько я трачу на еду", "intent": "visualization"},
    {"input": "Выведи график накоплений", "intent": "visualization"},
    {"input": "Хочу видеть визуализацию бюджета", "intent": "visualization"},
    {"input": "Покажи тренды моих расходов", "intent": "visualization"},
    {"input": "Статистика по месяцам", "intent": "visualization"},
    {"input": "Диаграмма моих целей", "intent": "visualization"},

    # === greeting (10 примеров) ===
    {"input": "Привет!", "intent": "greeting"},
    {"input": "Здравствуйте", "intent": "greeting"},
    {"input": "Добрый день", "intent": "greeting"},
    {"input": "Хай", "intent": "greeting"},
    {"input": "Приветствую", "intent": "greeting"},
    {"input": "Доброе утро", "intent": "greeting"},
    {"input": "Как дела?", "intent": "greeting"},
    {"input": "Здарова", "intent": "greeting"},
    {"input": "Привет, бот", "intent": "greeting"},
    {"input": "Добрый вечер", "intent": "greeting"},

    # === question (20 примеров) ===
    {"input": "Сколько у меня денег?", "intent": "question"},
    {"input": "Что такое бюджет?", "intent": "question"},
    {"input": "Как откладывать деньги?", "intent": "question"},
    {"input": "Почему я трачу так много?", "intent": "question"},
    {"input": "Как улучшить финансовое состояние?", "intent": "question"},
    {"input": "Что делать с долгами?", "intent": "question"},
    {"input": "Как считать расходы?", "intent": "question"},
    {"input": "Сколько я потратил вчера?", "intent": "question"},
    {"input": "Как работают цели?", "intent": "question"},
    {"input": "Можно ли изменить цель?", "intent": "question"},
    {"input": "Что такое финансовая подушка?", "intent": "question"},
    {"input": "Какие категории расходов бывают?", "intent": "question"},
    {"input": "Сколько откладывать в месяц?", "intent": "question"},
    {"input": "Почему накопления не растут?", "intent": "question"},
    {"input": "Как начать вести бюджет?", "intent": "question"},
    {"input": "Что делать с лишними деньгами?", "intent": "question"},
    {"input": "Как отслеживать траты?", "intent": "question"},
    {"input": "Где посмотреть историю?", "intent": "question"},
    {"input": "Что такое семантическая связь категорий?", "intent": "question"},
    {"input": "Как работает этот бот?", "intent": "question"},
]